name: BonezMC
version: '1.0'
main: net.protoser.bonezmc.BonezMC
api-version: '1.20'
authors: [Protoser]
website: djgamer.ddns.net

commands:
  equipbone:
    description: Put a bone on your helmet slot
    usage: /equipbone
