name: BonezMC
version: '1.1'
main: net.protoser.bonezmc.BonezMC
api-version: '1.21'
authors: [Protoser]
website: protoser.com

commands:
  equipbone:
    description: Put a bone on your helmet slot
    usage: /equipbone
